config/routes.rb
Examen2::Application.routes.draw do

  resources :authors do 
    get "mybooks" , on: :member
  end

  resources :books do
     resources :orders 
  end
  root 'home#index'

  get "/login" => "sessions#new"#, as: :patito
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates_uniqueness_of :email, :name
  validates_presence_of :email ,allow_blank: false
  
  has_many  :books
    
  has_secure_password
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title, :description, :price
  validates_numericality_of :price, greater_than: 0
  validates :description, length: { maximum: 200 }


  belongs_to :author
  has_many  :orders

  def self.categories_to_select
    ["AVENTURA", "ROMANCE","INFANTIL","EDUCATIVO","MOTIVACIONAL"]
  end

  def set_with_lempiras
    "#{price} Lps"
  end

  def  total_money(book)
    @total = Order.where("book_id = #{book.id}")
    @total.sum(:total)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates_presence_of :quantity
  validates_numericality_of :quantity, greater_than: 0
  default_scope :order => 'created_at DESC'
  
  around_create :order_total

  belongs_to :book


  

  def order_total
    if self.client.blank?
      self.client="Anomino"
    end

    self.total = self.book.price * self.quantity
    yield
  end

  def set_with_lempiras
    "#{total} Lps"
  end

  def decorate_created_at
    created_at.strftime(" %d %b %Y %l:%M %p")
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user#, :metodo1, :metodo2


  def current_user
    if session[:author_id].present?
      @current_user = Author.find(session[:author_id])
    end
  end

  def login(author)
    session[:author_id] = author.id
    redirect_to root_path
  end

  def authenticate
    unless current_user.present?
      redirect_to login_path
    end
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def new
    if current_user.present?
      redirect_to authors_path
    else
      @authors = Author.new
    end
  end

  def create
    @authors = Author.new(authors_params)

    if @authors.save
      AuthorMailer.welcome_email(@authors).deliver
      login(@authors)
    else
      render :new
    end
  end

  def mybooks
    @books=Book.where(author_id: params[:id])
  end

  def authors_params
      params.require(:author).permit!
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book=Book.order(:title) 

    @book = Book.includes(:author).order(:title)
  
    if params[:keyword].present?
      q = params[:keyword]
      @book = @book.joins(:author)
        .where("books.title LIKE '%#{q}%' OR authors.name LIKE '%#{q}%' OR books.price LIKE '%#{q}%' OR books.description LIKE '%#{q}%' OR books.category LIKE '%#{q}%'")
    end

    if request.xhr?
      render partial: "table", locals: {books: @book}
    end
  end

  def new
    @author = current_user
    @book = Book.new
  end

  def create
    @author = current_user

    @book = @author.books.build(book_params)

    if @book.save
      redirect_to mybooks_author_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @author = current_user
    @book = @author.books.find(params[:id])
  end

  def update
    @author = current_user
    @book = @author.books.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def show
    @book=Book.find(params[:id])
    @orders=@book.orders
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to mybooks_author_path(current_user.id)
  end

  private

    def book_params
      params.require(:book).permit!
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @order = Order.new
  end

  def create
    @book = Book.find(params[:book_id])

    @order = @book.orders.build(order_params)

    if @order.save
      OrderMailer.new_order(@book,@order).deliver
      redirect_to @book
    else
      render :new
    end
  end

  private

    def order_params
      params.require(:order).permit!
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate 

  def new
    if current_user.present?
      redirect_to root_path
    end
  end

  def create
    email = params[:session][:email]
    pass = params[:session][:password]

    @user = Author.find_by_email(email)

    if @user.present? && @user.authenticate(pass)
      login(@user)
    else
      redirect_to login_path, flash: {notice: "Author Email or Password is Incorrect"}
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def books
    Book.count
  end

  def authors
    Author.count
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/authors/mybooks.html.haml
%h1 Libros
%p Listado de libros

- if flash[:notice].present?
  .notice= flash[:notice]

- if @books.any?
  %table{border: "1"}
    %tr
      %th Autor
      %th Titulo
      %th Descripcion
      %th Precio
      %th Categoria
    = render @books
- else
  %em No hay ningun libro agregado

%br

= link_to "Nuevo Libro", new_book_path

app/views/authors/new.html.haml
%h2 New Author
%p Please enter your information
= render partial: "errors/errors", locals: {obj: @authors}

= form_for @authors do |f|
  %h2 User data
  .form_row
    = f.label :name, "Nombre"
    = f.email_field :name
  .form_row
    = f.label :email
    = f.email_field :email
  .form_row
    = f.label :password
    = f.password_field :password
  .form_row
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  #register
  = f.submit "Create"

app/views/books/_book.html.haml
%tr
  %td= book.author.name
  %td= link_to book.title, book
  %td= book.description
  %td= book.set_with_lempiras
  %td= book.category

  %td= link_to "Editar", edit_book_path(book)

  

app/views/books/_form.html.haml
= render partial: "errors/errors", locals: {obj: @book}

%p Ingresa los datos de la nueva cancion

= form_for @book do |f|


  .field
    = f.label :title, "Titulo"
    = f.text_field :title

  .field
    = f.label :description, "Descripcion"
    = f.text_field :description

  .field
    = f.label :price, "Precio"
    = f.text_field :price

  .field
    = f.label :category, "Categoria"
    = f.select :category, Book.categories_to_select, {}

  .field
    = f.submit

    =link_to "Cancel", mybooks_author_path(current_user.id)

app/views/books/_order.html.haml
- if orders.any?
  %h2 Ordenes

  %table{border:"1"}
    %tr
      %th Cliente
      %th Cantidad
      %th Total
      %th

    = render orders
 
- else
  %em Aun no tiene ordenes

app/views/books/_table.html.haml
%table{border: "1"}
  %tr
    %th Autor
    %th Titulo
    %th Descripcion
    %th Precio
    %th Categoria
  = render @book

app/views/books/edit.html.haml
%h2 Editar Libro
= form_for @book do |f|
  .field
    = f.label :title, "Titulo"
    = f.text_field :title

  .field
    = f.label :description, "Descripcion"
    = f.text_field :description

  .field
    = f.label :price, "Precio"
    = f.text_field :price

  .field
    = f.submit

app/views/books/index.html.haml
%h1 Libros
%p Listado de libros
- if flash[:notice].present?
  .notice= flash[:notice]

- if @book.any?
  = render partial: "shared/filter_form", locals: {form_path: books_path}
  .js_filtered_table
    = render partial: "table", locals: {bank_accounts: @book}
- else
  %em No hay ningun libro agregado

app/views/books/new.html.haml
%h1 New Book

= render "form"

app/views/books/show.html.haml
- if flash[:notice].present?
  .notice= flash[:notice]

%p
  %strong Autor
  = @book.author.name
%p
  %strong Titulo
  = @book.title
%p
  %strong Descripcion
  = @book.description

%p
  %strong Precio
  = @book.price

%p
  %strong Categoria
  = @book.category

%p
  %strong Total de ordenes recaudado
  = @book.total_money(@book)

  %h2 Detalle de Ordenes

  = render partial: "order", locals: { orders: @book.orders}

  %p= link_to "Nueva Orden",  new_book_order_path(@book)

-if  @book.author== current_user &&!(current_user.nil?)
  = link_to "Editar libro", edit_book_path(@book)
  = link_to "back", books_path(current_user.id)
- if @book.author== current_user &&@book.orders.count == 0
  = link_to "Borrar Libro", book_path(@book),method: :delete
  
 

app/views/home/index.html.haml
%h1 Home Page

%p Bienvenidos a nuestra biblioteca tenemos #{books} libros con una variedad de #{authors} autores

= image_tag("book.jpg")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblioteca</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="panelwrap">
  <div class="header">
    <div class="title">Biblioteca</div>

    <div class="header_right">
      
    </div>

    <div class="menu">
    <ul>
      <li><%= link_to "HOME", root_path %></li>
      <li><%= link_to "LIBROS", books_path %></li>
      <% if current_user.present? %>
        <li><%= link_to "MIS LIBROS", mybooks_author_path(current_user.id) %></li>
         <%=current_user.name %>
        <li><%= link_to "LOGOUT", logout_path,method: :delete %></li>

      <% else %>
        <li><%= link_to "LOGIN", login_path %></li>
        <li><%= link_to "SIGN UP", new_author_path %></li>
        <a>Iniciar Sesion</a>
      <% end %>
    </ul>
    </div>

  </div>

  <%= yield %>

</div>

</body>

app/views/orders/_form.html.haml
= render partial: "errors/errors", locals: {obj: @order}

%p Ingresa los datos de la nueva cancion

= form_for [@book, @order] do |f|


  .field
    = f.label :client, "Cliente"
    = f.text_field :client

  .field
    = f.label :quantity, "Cantidad"
    = f.number_field :quantity


  .field
    = f.submit

    =link_to "Cancel", books_path

app/views/orders/_order.html.haml
%tr
  %td= order.client
  %td= order.quantity
  %td= order.set_with_lempiras
  %td= order.decorate_created_at
  

app/views/orders/new.html.haml
%h1 Nueva Orden
= render "form"

app/views/shared/_filter_form.html.haml
= form_tag form_path, class: "js_filter_form", remote: true, method: :get do
  = text_field_tag :keyword, nil, placeholder: "Ingrese una palabra a buscar", class: "form_input"
  = submit_tag "Filtrar", class: "form_submit"